### ISSUE TITLE
'default' is not exported by worker

### ISSUE THREAD

**Issue by biosmanager** [Cloud-CNC/rollup-plugin-threads#1]
I get the following error when importing a TS worker like this in Svelte:

```
[!] Error: 'default' is not exported by src\workers\testWorker.ts, imported by src\App.svelte
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
src\App.svelte (7:9)
5:
6:   import { BlobWorker, spawn, Thread } from "threads";
7:   import WorkerTest from "./workers/testWorker";
```

Changing the extension of the worker to `.js` works (the worker only contains JS code currently).
`@ts-ignore` does not fix it.

The worker:

```
import { expose } from 'threads';

const worker = {
    echo(input) {
        return `Worker received: ${input}`;
    }
};

expose(worker);
```

My rollup config looks like this:

```
threads({
    //Exclude files
    exclude: [],

    //Include files
    include: ['src/workers/**/*.ts', 'src/workers/**/*.js'],

    //Rollup external configuration (Marks as external, helpful for Node runtimes)
    external: ['events'],

    //Child bundler plugins (Not reused; must be redefined if you want the same plugins)
    plugins: [
        resolve(),
        commonjs(),
        typescript({
            sourceMap: !production,
            inlineSources: !production
        })
    ]
}),
```

Does anybody know how to fix this? How can I import a TS worker?

**Comment by Wakeful-Cloud** [comment]
@biosmanager Can you post your tsconfig?

You can view a working example of a TS worker in the [cura-wasm](https://github.com/Cloud-CNC/cura-wasm) repository ([worker](https://github.com/Cloud-CNC/cura-wasm/blob/master/src/worker.ts#L190), [worker importer](https://github.com/Cloud-CNC/cura-wasm/blob/master/src/index.ts#L12), [rollup config](https://github.com/Cloud-CNC/cura-wasm/blob/master/rollup.config.js#L103)).

**Comment by biosmanager** [comment]
My tsconfig:

```
{
  "extends": "@tsconfig/svelte/tsconfig.json",

  "include": ["src/**/*"],
  "exclude": ["node_modules/*", "__sapper__/*", "public/*"]
}
```

The Svelte tsconfig:

```
{
  "$schema": "https://json.schemastore.org/tsconfig",
  "display": "Svelte",

  "compilerOptions": {
    "moduleResolution": "node",
    "target": "es2017",
    /** 
      Svelte Preprocess cannot figure out whether you have a value or a type, so tell TypeScript
      to enforce using `import type` instead of `import` for Types.
     */
    "importsNotUsedAsValues": "error",
    "isolatedModules": true,
    /**
      To have warnings/errors of the Svelte compiler at the correct position,
      enable source maps by default.
     */
    "sourceMap": true,
    /** Requests the runtime types from the svelte modules by default. Needed for TS files or else you get errors. */
    "types": ["svelte"],

    "strict": false,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  }
}
```

**Comment by Wakeful-Cloud** [comment]
@biosmanager I believe the problem is with your Rollup config, more specifically, the thread plugin isn't bundling your worker (But the parent rollup bundler is). I'm not sure why this works when changing the extension to `.js` though.

Can you try changing the thread plugin import setting from `include: ['src/workers/**/*.ts', 'src/workers/**/*.js']` to `include: ['**/src/workers/**/*.ts', '**/src/workers/**/*.js']` (Add `**` in front of all import paths)?

I'm assuming you have multiple workers, if that's incorrect, you need to adjust your import setting to something like `['**/worker.ts']`. Also, you shouldn't need to add both `.js` and `.ts` extensions, you only need the pre-compilation file extension (So for Typescript, you should only use `.ts`).

**Comment by biosmanager** [comment]
Adding `**` does unfortunately not fix it.
Currently I only have one worker but eventually there will be more.

**Comment by Wakeful-Cloud** [comment]
@biosmanager I've locally reproduced the issue, the problem actually lies with the Rollup plugin order. If I call the **thread** plugin constructor (`rollup-plugin-threads`) before the **typescript** plugin constructor (`rollup-plugin-typescript`), everything works; if I call it after the typescript plugin, ThreadJS complains about expose being called in the main thread. As far as not having a default export, you **can** export an empty string, number, or even `export default expose(worker);` from the worker or `@ts-ignore` it (But that didn't work for me with Svelte).

I'm going to add this to the documentation so this doesn't cause issues for others in the future.

**Comment by biosmanager** [comment]
@Wakeful-Cloud Changing the order of the threads() plugin fixed the default export and main thread issue! Thank you very much!
