### ISSUE TITLE
'threads' is not defined

### ISSUE THREAD

**Issue by masc-it** [Cloud-CNC/rollup-plugin-threads#2]
Hello,
I am trying to import your library into my project but it just cannot resolve it.

During the build ing process I have:
`(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
threads (imported by src/test.js)`

At runtime:
`ReferenceError: threads is not defined
    at main.js:6`
Any ideas?

**Comment by Wakeful-Cloud** [comment]
Are you able to post your full Roll-up configuration?
